### PR TITLE
clean away pointless arguments in tests

### PR DESCRIPTION
**Pull request by kilobyte**
These are fs_type (pmem/nonpmem — and thus running many tests twice), {,NON_}PMEM_FS_DIR (it's TEST_DIR now), test_type (all were mediums), rpmem stuff, anything python related.

3.5k more lines down the drain!

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/vmem/2)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
out_err_mt crashes on AppVeyor

**Comment by kilobyte** [comment]
Windows tests fixed, an assert and extra clean-ups added.

**Review by marcinslusarz — COMMENTED** [review]
> Reviewed 239 of 240 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/vmem/2)* status: 239 of 240 files reviewed, all discussions resolved

**Review by marcinslusarz — APPROVED** [review]
> Reviewed 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/vmem/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by marcinslusarz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/vmem/2)* status: 239 of 240 files reviewed, 1 unresolved discussion (waiting on @kilobyte and @marcinslusarz)

___
*[appveyor.yml, line 76 at r3](https://reviewable.io/reviews/pmem/vmem/2#-LrAQLO1A0OHpUrBFi_R:-LrAQLO1A0OHpUrBFi_S:b2ngvnt) ([raw file](https://github.com/pmem/vmem/blob/91e3f41bb0776d1875b553e8f1b7b5c083694735/appveyor.yml#L76)):*
> ```YAML
> 
>         if ($Env:CONFIGURATION -eq "Debug") {
>             ./RUNTESTS.ps1 -b debug -o 4m
> ```

...

**Review by kilobyte — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/vmem/2)* status: 238 of 240 files reviewed, 1 unresolved discussion (waiting on @marcinslusarz)

___
*[appveyor.yml, line 76 at r3](https://reviewable.io/reviews/pmem/vmem/2#-LrAQLO1A0OHpUrBFi_R:-LrAX-XD5Nm_Loshqt4C:b-896fix) ([raw file](https://github.com/pmem/vmem/blob/91e3f41bb0776d1875b553e8f1b7b5c083694735/appveyor.yml#L76)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

...
</blockquote></details>

Done.

**Review by marcinslusarz — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/vmem/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
